name: carpivara
description: "A new Flutter project."
publish_to: 'none' 
version: 0.0.1+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  get_it: ^8.2.0
  go_router: ^16.2.5
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.1
  permission_handler: ^12.0.1
  flutter_secure_storage: ^9.2.4
  flutter_dotenv: ^5.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env